#ifndef _USB_CONF_H
#define _USB_CONF_H

#include <stm32f4xx_usb_fs.h>

#define USB_DEVICE_IN_ENDPOINTS_NUMBER		USB_OTG_FS_DEVICE_MODE_FIFO_NUM
#define USB_DEVICE_OUT_ENDPOINTS_NUMBER		USB_OTG_FS_DEVICE_MODE_FIFO_NUM

#endif //_USB_CONF_H
